import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
        <body className="min-h-screen bg-gray-50 text-gray-900">
        <header className="border-b bg-white">
            <div className="mx-auto max-w-4xl px-4 py-3 flex items-center justify-between">
                <h1 className="font-semibold">Content Assistant</h1>
                <nav className="text-sm space-x-4">
                    <a href="/" className="hover:underline">Создать драфт</a>
                    <a href="/upload" className="hover:underline">Загрузка</a>
                    <a href="/drafts" className="hover:underline">Черновики</a>
                </nav>
            </div>
        </header>
        <main className="mx-auto max-w-4xl px-4 py-6">{children}</main>
        </body>
        </html>
    );
}
